name: clasePUC
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - watermark
  - pyproj
  - shapely
  - rpy2

# R base y herramientas
  - r-base=4.3
  - r-essentials
  - r-ggplot2
  - r-devtools
  - r-jsonlite
  - r-rcpp
  - r-dplyr
  - r-tidyverse
  - r-mass
  - r-matrix
  - r-sf
  - r-units
  - r-rmarkdown
  - r-rnaturalearth
  - r-here
  - r-httr
  - r-shinydashboard
  - r-leaflet
  - r-dplr
  - r-remotes       # para install_github


  # Pip (solo lo que no está en conda)
  - pip
  - pip:
      - pyleoclim
      # Si necesitas LiPD en Python usa 'lipd' (no 'pylipd'):
      - lipd

