name: clasePUC
channels:
  - conda-forge

dependencies:
  # ——— Python (mantengo 3.10 para que Binder NO cambie de base) ———
  - python=3.10
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - watermark
  - pyproj
  - shapely
  - rpy2

  # ——— R (usar conda para lo pesado y evitar compilar en CRAN) ———
  - r-base=4.3
  - r-essentials
  - r-ggplot2
  - r-devtools
  - r-jsonlite
  - r-rcpp
  - r-dplyr
  - r-tidyverse
  - r-mass
  - r-matrix
  - r-sf
  - r-units
  - r-rmarkdown
  - r-rnaturalearth
  - r-here
  - r-httr
  - r-shinydashboard
  - r-leaflet
  - r-dplr          # (dplR en CRAN -> r-dplr en conda-forge)
  - r-remotes
  - r-xml
  - r-lme4
  - r-nloptr

  # ——— pip (solo lo que no está en conda) ———
  - pip
  - pip:
      - pyleoclim
      - lipd            # LiPD para Python (no 'pylipd')

