name: clasePUC
channels:
  - conda-forge
  - defaults
dependencies:
  # Python y sus dependencias
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pylipd
  - watermark

  # R y sus dependencias
  - r-base=4.3.3
  - r-essentials
  - r-ggplot2
  - r-dplyr
  - r-sf
  - r-leaflet
  - r-rmarkdown
  - r-rnaturalearth
  - rpy2

  # pip debe estar definido antes de usarse
  - pip

  # pip packages (solo uno, indentado correctamente)
  - pip:
      - pyleoclim
      - pyproj
      - shapely

