name: clasePUC
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - watermark
  - pylipd
  - rpy2

  # R
  - r-base=4.3.3
  - r-essentials
  - r-ggplot2
  - r-dplyr
  - r-sf
  - r-leaflet
  - r-rmarkdown
  - r-rnaturalearth

  # Pip section (solo una vez)
  - pip
  - pip:
      - pyleoclim
      - pyproj
      - shapely

