name: clasePUC
channels:
  - conda-forge          # usa solo conda-forge para evitar conflictos geoespaciales
dependencies:
  # Python
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - watermark
  - pyproj               # mejor por conda que por pip
  - shapely              # mejor por conda que por pip
  - rpy2

  # R
  - r-base=4.3
  - r-essentials         # incluye IRkernel
  - r-ggplot2
  - r-dplyr
  - r-sf
  - r-leaflet
  - r-rmarkdown
  - r-rnaturalearth
  - r-remotes            # para instalar desde GitHub sin compilar toolchain

  # Sección pip (una sola vez y dentro de dependencies)
  - pip
  - pip:
      - pyleoclim        # aquí lo que NO está en conda
      # Si necesitas LiPD en Python usa 'lipd' (no 'pylipd'):
      - lipd

