name: clasePUC
channels:
  - conda-forge
  - defaults
dependencies:
  # Python y sus dependencias
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn

  # R y sus dependencias
  - r-base=4.3.3
  - r-essentials
  - r-ggplot2
  - r-dplyr
  - r-sf
  - r-leaflet
  - r-rmarkdown
  - r-rnaturalearth

  # Integración R y Python
  - rpy2

  # Dependencias adicionales de Python
  - pip:
    - pyleoclim
    - pyproj
    - shapely

